config/routes.rb
Rails.application.routes.draw do
  get '/welcome' => 'home#welcome'
  get '/sign_in' => 'home#sign_in'
  get '/sign_up' => 'home#sign_up'

  root 'home#sign_in'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end

  def sign_in
    render 'sign_in', layout: 'public'
  end

  def sign_up
    render 'sign_up', layout: 'public'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/login.html.erb
<div class="loginbox mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">

  <div class="panel panel-info" >
    <div class="panel-heading">
      <div class="panel-title">Sign In</div>
    </div>

    <div style="padding-top:30px" class="panel-body" >

      <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

      <form id="loginform" class="form-horizontal" role="form">

        <div style="margin-bottom: 25px" class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
          <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="username or email">
        </div>

        <div style="margin-bottom: 25px" class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
          <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
        </div>

        <div class="input-group">
          <div class="checkbox">
            <label>
              <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
            </label>
          </div>
        </div>

        <div class="login-btn form-group">
          <!-- Button -->
          <div class="col-sm-8 controls">
            <a id="btn-login" href="#" class="btn btn-success">Login  </a>
          </div>
          <div class="col-md-4">
            <a href="#">Forgot password?</a>
          </div>
        </div>

        <div class="form-group">
          <div class="col-md-12 control">
            <div class='signup-section'>
              Don't have an account!
              <%= link_to 'Sign Up Here', home_sign_up_path %>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/home/sign_in.html.erb
<div class="loginbox mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">

  <div class="panel panel-info" >
    <div class="panel-heading">
      <div class="panel-title">Sign In</div>
    </div>

    <div style="padding-top:30px" class="panel-body" >

      <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

      <form id="loginform" class="form-horizontal" role="form">

        <div style="margin-bottom: 25px" class="input-group">
          <span class="input-group-addon">
            <%= glyph(:user) %>
          </span>
          <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="username or email">
        </div>

        <div style="margin-bottom: 25px" class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
          <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
        </div>

        <div class="input-group">
          <div class="checkbox">
            <label>
              <input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
            </label>
          </div>
        </div>

        <div class="login-btn form-group">
          <!-- Button -->
          <div class="col-sm-8 controls">
            <a id="btn-login" href="#" class="btn btn-success">Login  </a>
          </div>
          <div class="col-md-4">
            <a href="#">Forgot password?</a>
          </div>
        </div>

        <div class="form-group">
          <div class="col-md-12 control">
            <div class='signup-section'>
              Don't have an account!
              <%= link_to 'Sign Up Here', sign_up_path %>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/home/sign_up.html.erb
<div class="signupbox mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
  <div class="panel panel-info">
    <div class="panel-heading">
      <div class="panel-title">Sign Up</div>
    </div>

    <div class="panel-body" >

      <form id="signupform" class="form-horizontal" role="form">

        <div id="signupalert" style="display:none" class="alert alert-danger">
          <p>Error:</p>
          <span></span>
        </div>

        <div class="form-group">
          <label for="email" class="col-md-3 control-label">Email</label>
          <div class="col-md-9">
            <input type="text" class="form-control" name="email" placeholder="Email Address">
          </div>
        </div>

        <div class="form-group">
          <label for="firstname" class="col-md-3 control-label">First Name</label>
          <div class="col-md-9">
            <input type="text" class="form-control" name="firstname" placeholder="First Name">
          </div>
        </div>

        <div class="form-group">
          <label for="lastname" class="col-md-3 control-label">Last Name</label>
          <div class="col-md-9">
            <input type="text" class="form-control" name="lastname" placeholder="Last Name">
          </div>
        </div>

        <div class="form-group">
          <label for="password" class="col-md-3 control-label">Password</label>
          <div class="col-md-9">
            <input type="password" class="form-control" name="passwd" placeholder="Password">
          </div>
        </div>

        <div class="form-group">
          <label for="icode" class="col-md-3 control-label">Confirm Password</label>
          <div class="col-md-9">
            <input type="password" class="form-control" name="passwd" placeholder="Password">
          </div>
        </div>

        <div class="form-group">
          <!-- Button -->
          <div class="col-md-offset-3 col-md-9">
            <button id="btn-signup" type="button" class="btn btn-info">
              <i class="icon-hand-right"></i>
              Sign Up
            </button>
            <div class="pull-right login-link">


            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="col-md-12 control">
            <div class='login-section'>
              Already have account?
              <%= link_to 'Login here.', sign_in_path %>
            </div>
          </div>
        </div>

      </form>
    </div>
  </div>
</div>

app/views/home/welcome.html.erb
<h1>Home#welcome</h1>
<p>Find me in app/views/home/welcome.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "LearningPortal" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">LearningPortal</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <footer>
      </footer>
    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "LearningPortal" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <div class="col-md-12 text-center">
        <h1>Learning Portal HSRW</h1>
      </div>
      <%= yield %>
    </div>
  </body>
</html>